[package]
name = "ntsc-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
env_logger = "0.10.0"
winit = "0.27.5"
pixels = "0.11.0"
image = "0.24.5"
rand = "0.8.5"
